server:
  port: 7011
  servlet:
    session:
      timeout:
        7200
  #SSL https证书配置
  ssl: 
  key-store: 1927045__51tour.com.pfx  #此文件放在/home/project/目录下
  key-store-password: iup0w7Go
spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  thymeleaf: 
    cache: false
  profiles: 
    active: dev
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
---
spring:
  profiles: dev #开发环境
  datasource: 
    url: jdbc:sqlserver://172.16.2.239:1433;Databasename=RealTourR8-test
    username: realtour
    password: ENC(VHSycrGLNcB7FexErFJNr006JGcDsL/P)
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    connection-timeout: 1800000
system-params: 
  imagePath: E://image//
  filePath: E://
---
spring:
  profiles: release #生产环境
  datasource: 
    url: jdbc:sqlserver://172.16.2.239:1433;Databasename=RealTourR8
    username: realtour
    password: ENC(VHSycrGLNcB7FexErFJNr006JGcDsL/P)
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    connection-timeout: 1800000
system-params: 
  imagePath: /home/wechat_image/
  filePath: /home/file/
